# Generated by Django 3.1.1 on 2020-10-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_has_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='high_res',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
